site_name: "Mkdocs Jupyter Pyodide"
site_url: https://ens-fr.gitlab.io/exp2
repo_url: https://gitlab.com/ens-fr/exp2
edit_uri: tree/main/docs/

docs_dir: docs

nav:
  - "🏡 Accueil": index.md
  #- ... | regex=^(?:(?!_REM.md).)*$
  - page test: Test_page.md
  - ide: ide.md
  - maths: maths.md
  - Mermaid: mermaid.md
  - notebook: notebook.ipynb
  - chapitre2:
      intro python: 02_chapitre_2/1_intro_python.md
      fonction: 02_chapitre_2/2_fonction.md
      Liste: 02_chapitre_2/3_liste.md


theme:
    name: material
    favicon: images/favicon.ico
    icon:
      logo: material/application-variable

    custom_dir: my_theme_customizations/

    font: false                     # RGPD ; pas de fonte Google
    language: fr                    # français
    palette:                        # Palettes de couleurs jour/nuit
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
            icon: material/weather-sunny
            name: Passer au mode nuit
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue
        accent: blue
        toggle:
            icon: material/weather-night
            name: Passer au mode jour
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.tracking
        - navigation.top
        - toc.integrate
        - header.autohide
        - content.code.annotate 




markdown_extensions:
    - meta
    - abbr

    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight:           # Coloration syntaxique du code
        auto_title: true
        auto_title_map:
            "Python": "🐍 Script Python"
            "Python Console Session": "🐍 Console Python"
            "Text Only": "📋 Texte"
            "E-mail": "📥 Entrée"
            "Text Output": "📤 Sortie"
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:              # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    


    - pymdownx.superfences:
        #preserve_tabs: true
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

    - pymdownx.superfences:
        custom_fences:
          - name: python
            class: python
            validator: !!python/name:markdown_exec.validator
            format: !!python/name:markdown_exec.formatter

    - pymdownx.arithmatex:
        generic: true
    - toc:
        permalink: ⚓︎
        toc_depth: 3

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lilabidi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/EddyLabidi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eddylabidi/


plugins:
  - search
  - markdown-exec
  - awesome-pages:
        collapse_single_pages: true
  - macros
  - tags:
      tags_file: tags.md
  


extra_javascript:
  - xtra/javascripts/mathjax-config.js                    # MathJax
  #- https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
  - https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js
  - https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js


extra_css:
  - xtra/stylesheets/qcm.css ##
  - xtra/stylesheets/ajustements.css  # ajustements

