site_name: MkDocs Jupyter pyodide with IDE

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
    - Home: index.md

plugins:
  - mkdocs-jupyter
  - search
  - macros
  - awesome-pages
      collapse_single_pages: true
  - exclude-search # exclusion de pages de la recherche
      exclude:
        - N*/*/*/*.md         # les REM
        - N*/*/*/*.py         # Les corrigés
        - xtra/*.md           # inutile de chercher cela

  
extra_javascript:
  - xtra/config.js                    # MathJax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - xtra/interpreter.js

extra_css:
  - xtra/pyoditeur.css
  - xtra/ajustements.css                      # ajustements

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lilabidi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/EddyLabidi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eddylabidi/





markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/lilabidi/mkdocs-learning"  target="_blank" rel="noopener">Eddy Labidi</a>